baseURL = "https://matheus-amaral06.github.io/Amaral-Cyber-Journal/"
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"
defaultContentLanguage = "en"
# website title
title = "My New Hugo Site"



[taxonomies]
# language code ["en", "zh-CN", "fr", "pl", ...]

# language name ["English", "简体中文", "Français", "Polski", ...]
# Menu config

[languages.en]
    weight = 1
    title = "Amaral Cyber Journal"
    languageCode = "en"
    languageName = "English"
    contentDir = "content/en/"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      name = "Posts"
      url = "/posts/"       # ← sem prefixo
    [[languages.en.menu.main]]
      weight = 2
      identifier = "about"
      name = "About"
      url = "/about/"       # ← sem prefixo

  [languages.pt-br]
    weight = 2
    title = "Amaral Cyber Journal"
    languageCode = "pt-BR"
    languageName = "Português"
    contentDir = "content/pt-br/"
    [[languages.pt-br.menu.main]]
      weight = 1
      identifier = "posts"
      name = "Posts"
      url = "/posts/"       # ← sem prefixo, Hugo adiciona /pt-br/ sozinho
    [[languages.pt-br.menu.main]]
      weight = 2
      identifier = "sobre"
      name = "Sobre"
      url = "/about/"  
[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "light"
  title = "Amaral Cyber Journal"
  images = ["/logo.png"]



[markup]
  [markup.highlight]
    noClasses = false

[caches]
    [caches.images]
        dir = ':cacheDir/images'


